name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          GOPATH: /home/runner/work/kubernetes/go
          GOBIN: /home/runner/work/kubernetes/go/bin

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          path: go/src/k8s.io/kubernetes

      - name: install kubectl
        uses: Azure/setup-kubectl@v1

        # https://github.com/kubernetes-sigs/kind/pull/825
      - name: Build kind binary from master
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@master

      - name: Build kind node-image
        run: |
          $GOBIN/kind version
          # https://github.com/kubernetes-sigs/kind/pull/819
          GOFLAGS= $GOBIN/kind build node-image

      - name: Create kind cluster
        run: |
          cat <<EOF > "kind-config.yaml"
          # config for 1 control plane node and 2 workers (necessary for conformance)
          kind: Cluster
          apiVersion: kind.sigs.k8s.io/v1alpha3
          nodes:
          - role: control-plane
          - role: worker
          - role: worker
          EOF
          $GOBIN/kind create cluster --image kindest/node:latest -v=3 --wait=1m --config=kind-config.yaml
          kubectl version
          kubectl get nodes

      - name: Run tests
        run: |
          ./hack/ginkgo-e2e.sh --provider=skeleton --num-nodes=2 --ginkgo.focus=\[Conformance\] --report-dir=_artifacts --v 6
          echo $KUBEROOT
        working-directory: "/home/runner/work/kubernetes/go/src/k8s.io/kubernetes"
        env:
          GINKGO_PARALLEL: "y"
          KUBERNETES_CONFORMANCE_TEST: "y"
          KUBERNETES_PROVIDER: skeleton

      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: /home/runner/work/kubernetes/go/src/k8s.io/kubernetes/_artifacts
