name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
      env:
        GOPATH: /__w/kubernetes/go/
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          path: go/src/k8s.io/kubernetes

      - name: Get Kind
        run: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-$(uname)-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin

      - name: Build node-image
        run: |
          kind build node-image
