name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          GOPATH: /home/runner/work/kubernetes/go
          GOBIN: /home/runner/work/kubernetes/go/bin

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          path: go/src/k8s.io/kubernetes

      - name: install kubectl
        uses: Azure/setup-kubectl@v1

      - name: Build kind from master
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@master

      - name: Build kind node-image
        run: |
          $GOBIN/kind version
          GOFLAGS= $GOBIN/kind build node-image

      - name: Build kind node-image
        run: |
          $GOBIN/kind version
          GOFLAGS= $GOBIN/kind create cluster --image kindest/node:latest
          kubectl cluster-info --context kind-kind
